repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
---
releases:
- name: mongodb
  chart: bitnami/mongodb
  namespace: mongodb
  needs: []
  values: []
- name: kafka
  chart: bitnami/kafka
  namespace: kafka
  needs:
  - mongodb/mongodb
  - kafka/kafka
  values:
  - values.yaml
