repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
---
releases:
- name: mongodb
  chart: bitnami/mongodb
  namespace: mongodb
- name: kafka
  chart: bitnami/kafka
  namespace: kafka
